### ISSUE TITLE
Python 3.8 test failures

### ISSUE THREAD

**Issue by tirkarthi** [mozman/svgwrite#51]
In Python 3.8 with https://bugs.python.org/issue34160 the order of attributes for xml is preserved and not sorted like in Python 3.7. So using `toString()` now returns the order preserved results. This results in tests to fail with Python 3.8. Attached is a build log of test failures.

Thanks

[svgwrite.log](https://github.com/mozman/svgwrite/files/3316585/svgwrite.log)

**Comment by tirkarthi** [comment]
Was this fixed in develop branch?

**Comment by mozman** [comment]
now!

**Comment by tirkarthi** [comment]
Thank you.

**Comment by vojtechtrefny** [comment]
I think this isn't fixed yet. I've tested 1.3.0 with python 3.8 a the tests are still failing.

I was able to fix most of the failures with a [simple change](https://vtrefny.fedorapeople.org/patches/0001-Manually-sort-XML-attributes.patch), only test failing right now is the pretty print one. Looks like `minidom.parseString` also adds the attributes in "wrong" order.
